### PR TITLE
Fix unexpected state change

### LINKED ISSUE #158: Fix unlimited block creation without state change
for any reason, the state implemented with tendermint iavl changes continuously, resulting in the change of 'appHash' which triggers a new block creation ..

### PR DESCRIPTION
**Pull request by h0n9**
- ignore setting 0 value to store(update test codes)
- fix app_config to get applied properly
- add "config/lockup_period" property to test_script/genesis.json

resolves https://github.com/amolabs/amoabci/issues/158

### CODE REVIEW

**Comment by h0n9** [comment]
It seems necessary to update integration test of `test_script/all.sh` to test `lockup_period`, `locked` and `unlocked` stakes. But, it is recommended to consider the test can take lots of time to wait for `locked` stakes to get `unlocked`.

File: amo/tx/transfer.go [hunk 1]
```diff
@@ -63,5 +63,8 @@ func (t *TxTransfer) Execute(store *store.Store) (uint32, string, []tm.KVPair) {
 	toBalance.Add(&txParam.Amount)
 	store.SetBalance(t.GetSender(), fromBalance)
 	store.SetBalance(txParam.To, toBalance)
-	return code.TxCodeOK, "ok", nil
+	tags := []tm.KVPair{
```
Comment (Lbird) [inline amo/tx/transfer.go]: Remove this. This should be handled in other PR.

**Review by Lbird — CHANGES_REQUESTED** [review]

**Review by Lbird — APPROVED** [review]
