### PR TITLE
Bug/290 panic properly for unsupoorted versions

### LINKED ISSUE #290: Panic properly for unsupported versions

### PR DESCRIPTION
**Pull request by h0n9**
resolves https://github.com/amolabs/amoabci/issues/290

### CODE REVIEW

File: amo/amo.go [hunk 1]
```diff
@@ -23,11 +24,18 @@ import (
 )
 
 const (
-	// versions
+	// current versions
 	AMOAppVersion      = "v1.7.5"
 	AMOProtocolVersion = uint64(0x4)
+
```
Comment (Lbird) [inline amo/amo.go]: remove this gap

**Review by Lbird — APPROVED** [review]
